-- First, remove the table if it exists
DROP TABLE IF EXISTS bookmarks;

-- Create the table anew
CREATE TABLE bookmarks (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  description TEXT,
  rating INTEGER CHARACTER(1) DEFAULT 3
);

-- insert some test data
-- Using a multi-row insert statement here
INSERT INTO bookmarks (title, url, description, rating)
VALUES
  ('Google', 'https://www.google.com', 'Its like Bing', 4),
  ('Firefox', 'https://www.firefox.com', 'Its like Chrome', 5),
  ('Reddit', 'https://www.reddit.com', 'Its like 2004 online forums', 3),
  ('Thinkful', 'https://www.thinkful.com', 'Its awesome', 5),
  ('Stackoverflow', 'https://www.stackoverflow.com', 'Its like Google', 5),
  ('Github', 'https://www.github.com', 'Its like Bitbucket', 5),
  ('Amazon', 'https://www.amazon.com', 'Its like Costco for the internet', 3),
  ('Google', 'https://www.google.com', 'Its like Ask Jeeves', 1),
  ('Google', 'https://www.google.com', 'Its like Cortana?', 5),
  ('Google', 'https://www.google.com', 'Its like Siri', 2),
  ('Google', 'https://www.google.com', 'Its like the yellow pages', 1);